version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS
    volumes:
      - ".docker/mssql/data:/var/opt/mssql/data"
      - ".docker/mssql/log:/var/opt/mssql/log"
      - ".docker/mssql/secrets:/var/opt/mssql/secrets"
